### ISSUE TITLE
about nodejs-path

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [javascript-society/javascript-path#34]
When you will add the nodejs-path? Because I'd like to submit some posts and ebooks about node.js :)

**Comment by ericdouglas** [comment]
@caio-ribeiro-pereira if you want to help build it I can give you permissions to start the creation of this new path. Sounds good to you?

**Comment by caio-ribeiro-pereira** [comment]
Sure of course! Give me the permission and I will build it during this week :)
Thanks!

**Comment by ericdouglas** [comment]
@caio-ribeiro-pereira done :white_check_mark:

**Comment by ericdouglas** [comment]
@caio-ribeiro-pereira I removed the `node-path` repository because currently is **impossible** to create such repository in the same way that the `javascript-path` was built. We don't have enough free books do to so.

I would suggest to you to write in a gist file a structure of topics that a good node-path must contain, and after this, [we all](https://github.com/javascript-society/javascript-path/watchers) can iterate through it and start making suggestions.

As our organization has an inclination to provide free resources, for a good node-path I think would be interesting to have a list of articles to be the essential path, and optionally we can have a list of courses and books, maybe in different files, `books.md` and `courses.md`, for example.

Thank you so much for your interest in help us :pray:
